export const DEFAULT_PERCENT_PLACEHOLDER = '0';
export const DEFAULT_PERCENT_DECIMAL_PRECISION = 2;
export const DEFAULT_PERCENT_PASTE_MAX = 100;
export const DEFAULT_PERCENT_TYPING_MAX_INTEGER_DIGITS = 3;
export const MAX_PERCENT_RAW_LENGTH = 64;
