#!/usr/bin/env sh

echo "HUSKY PRE-COMMIT KØRER"

# Stop på første fejl
set -e

# Generér ny versionsfil
node scripts/generate-version.js

# Tilføj filen igen til commit
git add src/config/version.js
